### ISSUE TITLE
QGis desktop - Lizmap error

### ISSUE THREAD

**Issue by nrohnie** [3liz/lizmap-web-client#3964]
### What is the bug?

After creating sqllite database, import Edigeo and Majics data, a error appear when clicking on Lizmap :

AttributeError: 'QgsLayerTreeNode' object has no attribute 'layerId' 

### Steps to reproduce the issue

1. QGis Deskop
2. Internet
3. Lizmap
4. => The error occur....

### Versions

**Versions :**

* Lizmap Web Client : 3.6.7
* Lizmap plugin : 3.18.1
* QGIS Desktop : 3.22.4
* QGIS Server : 3.22.4
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.18.2
* QGIS Server plugin lizmap_server : 2.8.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Linux Mint 21 Vanessa

### Browsers

Chrome

### Browsers version

Version 119.0.6045.123

### Relevant log output

```shell
Une erreur est survenue lors de l'éxécution du code Python: 

AttributeError: 'QgsLayerTreeNode' object has no attribute 'layerId' 
Traceback (most recent call last):
  File "/home/stephan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lizmap/plugin.py", line 3645, in save_cfg_file
    ogc_projet_validity.add_shortnames()
  File "/home/stephan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lizmap/ogc_project_validity.py", line 35, in add_shortnames
    existing, duplicated = self.existing_shortnames()
  File "/home/stephan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lizmap/ogc_project_validity.py", line 68, in existing_shortnames
    existing = self._read_all_shortnames(layer_tree, [])
  File "/home/stephan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lizmap/ogc_project_validity.py", line 89, in _read_all_shortnames
    self._read_all_shortnames(child, existing_shortnames)
  File "/home/stephan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lizmap/ogc_project_validity.py", line 81, in _read_all_shortnames
    layer = self.project.mapLayer(child.layerId())
AttributeError: 'QgsLayerTreeNode' object has no attribute 'layerId'


Version de Python : 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] 
Version de QGIS : 3.22.4-Białowieża Białowieża, exported 

Chemin Python :
/usr/share/qgis/python
/home/stephan/.local/share/QGIS/QGIS3/profiles/default/python
/home/stephan/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.10/dist-packages
/home/stephan/.local/share/QGIS/QGIS3/profiles/default/python
/home/stephan/lizmap/custom_repository
```

**Comment by Gustry** [comment]
This issue is in the wrong GitHub repository.
