### ISSUE TITLE
[Bug]: n:m relation not shown correctly

### ISSUE THREAD

**Issue by tbnobody** [3liz/lizmap-web-client#4315]
### What is the bug? (in English)

A n:m relation is not shown correctly in the web frontend. It just shows the pivot table
![image](https://github.com/3liz/lizmap-web-client/assets/1753222/b50c373c-80a1-4e50-89aa-76d461062b5c)

The table is defined as follows.
![image](https://github.com/3liz/lizmap-web-client/assets/1753222/0504224f-11d8-40d0-a98f-bfefcee677cb)

![image](https://github.com/3liz/lizmap-web-client/assets/1753222/9ea109fe-e221-4c9a-a6f2-ea3ca6d7576c)

The following exception is thrown by the lizmap server plugin (might be related to #4307):
```
Mar 19 21:54:54 boromir spawn-fcgi[49512]: 21:54:54 CRITICAL Lizmap[49512]: Critical exception:
Mar 19 21:54:54 boromir spawn-fcgi[49512]: 'Relation'
Mar 19 21:54:54 boromir spawn-fcgi[49512]: Traceback (most recent call last):
Mar 19 21:54:54 boromir spawn-fcgi[49512]:   File "/opt/qgis_server/plugins/lizmap_server/get_feature_info.py", line 178, in responseComplete
Mar 19 21:54:54 boromir spawn-fcgi[49512]:     features = self.feature_list_to_replace(cfg, project, relation_manager, xml)
Mar 19 21:54:54 boromir spawn-fcgi[49512]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 19 21:54:54 boromir spawn-fcgi[49512]:   File "/opt/qgis_server/plugins/lizmap_server/get_feature_info.py", line 121, in feature_list_to_replace
Mar 19 21:54:54 boromir spawn-fcgi[49512]:     html_content = Tooltip.create_popup_node_item_from_form(layer, root, 0, [], '', relation_manager)
Mar 19 21:54:54 boromir spawn-fcgi[49512]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 19 21:54:54 boromir spawn-fcgi[49512]:   File "/opt/qgis_server/plugins/lizmap_server/tooltip.py", line 180, in create_popup_node_item_from_form
Mar 19 21:54:54 boromir spawn-fcgi[49512]:     h = Tooltip.create_popup_node_item_from_form(layer, n, level, headers, html, relation_manager)
Mar 19 21:54:54 boromir spawn-fcgi[49512]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 19 21:54:54 boromir spawn-fcgi[49512]:   File "/opt/qgis_server/plugins/lizmap_server/tooltip.py", line 116, in create_popup_node_item_from_form
Mar 19 21:54:54 boromir spawn-fcgi[49512]:     relation = relation_manager.relation(widget_config['Relation'])
Mar 19 21:54:54 boromir spawn-fcgi[49512]:                                          ~~~~~~~~~~~~~^^^^^^^^^^^^
Mar 19 21:54:54 boromir spawn-fcgi[49512]: KeyError: 'Relation'
```

Therefore I changed the `tooltip.py` in line 114 (bad hack, I know)
```python
            if widget_type == 'RelationReference':
                referenced_layer = None
                if widget_config['Relation']
                    relation = relation_manager.relation(widget_config['Relation'])
                    referenced_layer = relation.referencedLayer()
```

Now i got the following log output:
```
Mar 19 21:57:27 boromir spawn-fcgi[49647]: 21:57:27 WARNING [49647]: Layer trail_supervisor, field tail_id: Missing Relation in configuration
Mar 19 21:57:27 boromir spawn-fcgi[49647]: 21:57:27 WARNING [49647]: Layer trail_supervisor, field supervisor_id: Missing Relation in configuration
```

Not sure why the relation is missing. The layer are shared via WFS:
![image](https://github.com/3liz/lizmap-web-client/assets/1753222/63c6a731-6b6f-4a34-876b-675c24ab6ee4)

### Steps to reproduce the issue

Also covered above...

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.5
* Lizmap plugin : 4.2.7
* QGIS Desktop : 3.34.4
* QGIS Server : 3.36.0
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : no
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 11

### Browsers

Chrome

### Browsers version

Vivaldi 6.5.3206.53 (Stable channel) (32-Bit)

**Comment by tbnobody** [comment]
It seems to work now, but I had to add the primary id to all three layers in the attributes form editor (e.g. `id`):
![image](https://github.com/3liz/lizmap-web-client/assets/1753222/4af234e5-0551-4ed3-bb9d-25d96958528c)

**Comment by timbo-barnes** [comment]
I can confirm that this is still the case in LMWC 3.9.3:
If you have multiple relations pointing to the same child table, the relation won't show in Lizmap unless you expose the primary key (i.e. added to the drag and drop form)
